### ISSUE TITLE
Add sample for handler derivation

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AuthSamples#19]
Deriving from an auth handler and overriding methods is a theoretical avenue of extensibility, but we've never tried it end-to-end. E.g. how do you register your derived handler, or are there any useful methods to override? I expect the current handlers do not have a sufficiently granular overridable API surface for you to be able to make meaningful changes this way. The events are a far more consumable extensibility model.

**Comment by HaoK** [comment]
I'm assuming you haven't started on this yet have you @Tratcher ?  I'll take a look if not

**Comment by Tratcher** [comment]
Ho

**Comment by HaoK** [comment]
https://github.com/aspnet/AuthSamples/pull/47

**Comment by HaoK** [comment]
This wasn't compelling enuf to do, we can revisit this in the future if it comes important.  We'd likely need to make some product changes to make it more useful
