### ISSUE TITLE
Add a dynamic scheme with dynamic options sample

### ISSUE THREAD

**Issue by HaoK** [aspnet/AuthSamples#3]
https://github.com/aspnet/Security/issues/1533#issuecomment-344389963

**Comment by Jenan** [comment]
@HaoK when are you planning to add this sample? :)

**Comment by HaoK** [comment]
Probably in december

**Comment by HaoK** [comment]
@Jenan see https://github.com/aspnet/AuthSamples/pull/22

**Comment by HaoK** [comment]
a3df6a7bf9fc3f3dcd1164c0dcd90af21e3820f1
