### ISSUE TITLE
Add dynamic IPolicyProvider AuthZ sample

### ISSUE THREAD

**Issue by HaoK** [aspnet/AuthSamples#30]
https://github.com/aspnet/Security/issues/1689#issuecomment-372711031

**Comment by mjrousos** [comment]
In case it's useful, I have a basic `IAuthorizationPolicyProvider` sample [here](https://github.com/mjrousos/IAuthorizationPolicyProviderSample).

**Comment by HaoK** [comment]
Being worked on by @mjrousos in PR: https://github.com/aspnet/AuthSamples/pull/31

**Comment by HaoK** [comment]
Merged https://github.com/aspnet/AuthSamples/pull/31
